### ISSUE TITLE
!!! Implement decentralized sequencers

### ISSUE THREAD

**Issue by chengwenxi** [mantlenetworkio/mantle#15]
## Summary

Implement decentralized sequencers, there are two main goals here:

* Anyone can participate in the sequencer set as a L2 block producer.
* Reduce MEV, each sequencer participating in the consensus process is able to determine transaction ordering.

### Layer 1

* [x] Sequencer set selection on L1 ,#139 
  * Register Sequencer with mintAddress(l2geth/miner/miner.go#Miner.coinbase) and nodeID(l2geth/p2p/encode/node.go#Node.id).
  * Set Scheduler with nodeID.

#### L2geth

* [ ] Rotation mechanism
  * [x] Weighted round-robin algorithm, #16
  * [x] Get Sequencer set from L1's contract, and update mintpower each epoch #55 
  * [x] Scheduler broadcast producers #197 
  * [x] Switching sequencer for liveless issue  
    * [x] ~~Heartbeat: Listen to the connection between Scheduler and Sequencer via l2/geth/p2p pingpong mechanism(Identity authentication by nodeID).~~
    * [x] Timeout: Sequencer does not commit the block to the scheduler on time(Identity authentication by mintAddress).
* [x] Convert l1->l2 transactions and submit these transactions to L2 : TBD
* [ ] Add scheduler consensus in l2geth/consensus:
  * [x] Implement consensus interface to produce block, #59
  * [x] Get the block producer from scheduler, #60
  * [x] Get blocks from scheduler/l2geth (Identity authentication by nodeID), #61

**Comment by renweifeng99** [comment]
[Sequencer Contract#231](https://github.com/mantlenetworkio/mantle/issues/231)

**Comment by Kukoomomo** [comment]
Scheduler broadcast producers #197

**Comment by Kukoomomo** [comment]
New tasks for Implement decentralized  sequencer 

### Scheduler
 * [ ] Sequencer Health Evaluation Service
 * [ ] The Scheduler obtains the latest sequencer set and sequencer health from L1 every day, and uses Tendermint's mechanism to select block producers to calculate the batch period
 * [ ] Send BatchPeriodStartMsg, BatchPeriodEndMsg and FraudProofReorgMsg by p2p
#### Coordinate the sequencer block production service
   * [ ] Take a batch period from the batch period set, then construct BatchPeriodStartMsg and broadcast it
   * [ ] Enter the state of waiting for the block, verify the block produced by the sequencer, and add a confirmation signature
   * [ ] Construct BatchPeriodEndMsg to terminate the current batch period
 * [ ] Implement the FraudProofReorgRequest service. When receiving a reorg request with a tss signature, construct a FraudProofReorgMsg and broadcast it

### Sequencer
 * [ ] Receives BatchPeriodStartMsg and BatchPeriodEndMsg by p2p
 * [ ] Process BatchPeriodStartMsg, start to take out the transactions in the txpool and generate blocks in the form of one transaction per block
 * [ ] Process BatchPeriodEndMsg and reorg the blocks not confirmed by schduler. And store the schduler signature in BatchPeriodEndMsg into the local block header
 * [ ] Handle FraudProofReorgMsg, reorg to the specified height, and no longer synchronize blocks whose block hash is fraudNextBlockHash
