### ISSUE TITLE
Gas fee & Distribution of rewards

### ISSUE THREAD

**Issue by curryxbo** [mantlenetworkio/mantle#25]
- [x] Erc20 token replacement
- [x] Add  token price service for GasPriceOracle #28 
- [x] Distribution of Tss rewards

**Comment by curryxbo** [comment]
too old
