### ISSUE TITLE
sequencer:The L1ToL2 transaction is processed using the Scheduler signature

### ISSUE THREAD

**Issue by curryxbo** [mantlenetworkio/mantle#378]
In the decentralized Sequencer scenario, in order to prevent the transactions from being forged, we decide to let the Scheduler sign the transactions of type L1ToL2.
The following requirements will be developed based on [[features/decentralized-sequencers]](https://github.com/mantlenetworkio/mantle/tree/features/decentralized-sequencers)
- [ ] The private key of the Scheduler is used to sign transactions of type L1ToL2
- [ ] The signature for a transaction of type L1ToL2 is verified during ApplyTx
- [ ] Open the gasFee whitelist to the Scheduler's Address, if necessary, to prevent the network from charging the Scheduler GasFee

**Comment by curryxbo** [comment]
@aodhgan Due to some changes to the schema, the scheduler unified production blocks, so this signature is now unnecessary，so the Issue will be closed
