### ISSUE TITLE
Sequencer: Implement  Scheduler schedule sequencer rollback

### ISSUE THREAD

**Issue by curryxbo** [mantlenetworkio/mantle#450]
- [x] #451
- [x] #452
- [x] Add rollbackIndex to the block header. Add rollbackIndex verification to the block output flow
- [x] Confirm whether there is an active synchronization mechanism for backward blocks
- [ ] P2P actively requests rollbackStates
